[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@8.15.4",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]
